<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageTransitivePinningEnabled>true</CentralPackageTransitivePinningEnabled>
  </PropertyGroup>

  <ItemGroup>
    <PackageVersion Include="BenchmarkDotNet" Version="0.15.8" />
    <PackageVersion Include="Kiji" Version="0.1.0-preview.2" />
    <PackageVersion Include="Markdig" Version="0.44.0" />
    <PackageVersion Include="Microsoft.Testing.Platform" Version="1.8.2" />
    <PackageVersion Include="MinVer" Version="7.0.0" />
    <PackageVersion Include="SixLabors.ImageSharp" Version="3.1.12" />
    <PackageVersion Include="System.IO.Hashing" Version="10.0.9" />
    <PackageVersion Include="xunit.v3" Version="3.0.1" />
    <PackageVersion Include="YamlDotNet" Version="16.3.0" />
  </ItemGroup>
</Project>
