using Microsoft.AspNetCore.Components;
using Microsoft.AspNetCore.Components.Rendering;

namespace Kiji.SyntheticSite;

/// <summary>
/// Default layout for the synthetic site: header with navigation, main slot, footer.
/// </summary>
public sealed class MainLayout : LayoutComponentBase
{
    protected override void BuildRenderTree(RenderTreeBuilder builder)
    {
        builder.OpenElement(0, "div");
        builder.AddAttribute(1, "class", "site");

        builder.OpenElement(2, "header");
        builder.OpenElement(3, "a");
        builder.AddAttribute(4, "href", "/");
        builder.AddContent(5, "Kiji Bench");
        builder.CloseElement();
        builder.OpenElement(6, "nav");
        builder.OpenElement(7, "a");
        builder.AddAttribute(8, "href", "/blog/");
        builder.AddContent(9, "Blog");
        builder.CloseElement();
        builder.CloseElement();
        builder.CloseElement();

        builder.OpenElement(10, "main");
        builder.AddContent(11, Body);
        builder.CloseElement();

        builder.OpenElement(12, "footer");
        builder.AddContent(13, "Generated by the Kiji synthetic benchmark site.");
        builder.CloseElement();

        builder.CloseElement();
    }
}
