using System.Collections;
using System.Collections.Frozen;
using System.Diagnostics.CodeAnalysis;
using Kiji.Hosting;
using Kiji.Generation;
using System.Text;
using Kiji.Rendering;

namespace Kiji;

/// <summary>A lazily loaded, dependency-aware dictionary of site content.</summary>
/// <remarks>
/// Resolve it through dependency injection. Keys are opaque references generated by Kiji for
/// looking an item up again in this dictionary; they are not URLs, slugs, domain identifiers,
/// or persistent identifiers.
/// </remarks>
public sealed class ContentDictionary<T> : IReadOnlyDictionary<string, T>
    where T : class
{
    private readonly string _sourceId;
    private readonly ContentRuntime _runtime;
    private readonly Func<IServiceProvider, IReadOnlyList<(string Key, T Item, string? Digest)>> _load;

    internal ContentDictionary(
        ContentRuntime runtime,
        Func<IServiceProvider, IReadOnlyList<(string Key, T Item, string? Digest)>> load,
        string contentSetScope = "")
    {
        _runtime = runtime;
        _load = load;
        _sourceId = typeof(T).FullName + ":" + contentSetScope;
        runtime.Dependencies.Register(_sourceId, CollectionDigest);
        runtime.Dependencies.RegisterSource(_sourceId, key => Materialized.Index.GetValueOrDefault(key).Digest);
    }

    /// <summary>
    /// The number of items in the dictionary.
    /// </summary>
    public int Count => Observed.Entries.Count;

    /// <summary>
    /// Every opaque key, in source order.
    /// </summary>
    public IEnumerable<string> Keys => Observed.Entries.Select(static entry => entry.Key);

    /// <summary>
    /// Every item, in source order.
    /// </summary>
    public IEnumerable<T> Values => Observed.Entries.Select(static entry => entry.Value);

    /// <summary>
    /// The item with the given key, compared case-insensitively.
    /// </summary>
    /// <exception cref="KeyNotFoundException">No item carries that key.</exception>
    public T this[string key] => TryGetValue(key, out var item)
        ? item
        : throw new KeyNotFoundException($"Content item with key '{key}' was not found.");

    /// <summary>
    /// Finds an item by its key, compared case-insensitively.
    /// </summary>
    public bool TryGetValue(string key, [NotNullWhen(true)] out T? item)
    {
        ArgumentNullException.ThrowIfNull(key);

        var materialized = Materialized;
        if (!materialized.Index.TryGetValue(key, out var entry))
        {
            // A miss still observed the key set, so it is only valid while the key set
            // holds — that is the content set, not any one file.
            MarkContentSetDependency();
            item = null;
            return false;
        }

        item = entry.Item;
        var dependencies = PageRenderContext.Current?.Dependencies;
        if (dependencies is not null)
        {
            // The lookup depends on collection membership as well as file contents:
            // a loader can filter out an unchanged file in the next snapshot.
            dependencies.AddValue(_sourceId + "/" + key.ToUpperInvariant(), entry.Digest);
        }
        return true;
    }

    /// <summary>
    /// Whether an item with the given key exists.
    /// </summary>
    public bool ContainsKey(string key)
    {
        return TryGetValue(key, out _);
    }

    /// <inheritdoc/>
    public IEnumerator<KeyValuePair<string, T>> GetEnumerator()
    {
        return Observed.Entries.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    private MaterializedContent Materialized => _runtime.GetOrMaterialize(this, Materialize);

    /// <summary>
    /// The dictionary as seen by a member that exposes its shape (count, keys, values,
    /// enumeration). Observing the shape couples the page to the content set: a list
    /// page has to reflect items being added and removed, not just edited. Keyed
    /// lookups deliberately go through <see cref="Materialized"/> instead.
    /// </summary>
    private MaterializedContent Observed
    {
        get
        {
            MarkContentSetDependency();
            return Materialized;
        }
    }

    private void MarkContentSetDependency()
    {
        PageRenderContext.Current?.Dependencies?.AddValue(_sourceId, CollectionDigest());
    }

    private string? CollectionDigest()
    {
        return Materialized.CollectionDigest.Value;
    }

    private MaterializedContent Materialize(IServiceProvider services)
    {
        var loaded = _load(services);

        var index = new Dictionary<string, (T Item, string? Digest)>(loaded.Count, StringComparer.OrdinalIgnoreCase);
        var entries = new KeyValuePair<string, T>[loaded.Count];
        for (var i = 0; i < loaded.Count; i++)
        {
            var (key, item, digest) = loaded[i];
            if (string.IsNullOrWhiteSpace(key))
            {
                throw new InvalidOperationException(
                    $"The internal content loader for '{typeof(T).Name}' produced an empty key.");
            }

            if (!index.TryAdd(key, (item, digest)))
            {
                throw new InvalidOperationException(
                    $"The internal content loader for '{typeof(T).Name}' produced duplicate key '{key}'.");
            }

            entries[i] = new KeyValuePair<string, T>(key, item);
        }

        return new MaterializedContent(
            entries,
            index.ToFrozenDictionary(StringComparer.OrdinalIgnoreCase));
    }

    private sealed class MaterializedContent(
        IReadOnlyList<KeyValuePair<string, T>> entries,
        FrozenDictionary<string, (T Item, string? Digest)> index)
    {
        public Lazy<string?> CollectionDigest { get; } = new(() =>
        {
            var builder = new StringBuilder();
            foreach (var entry in entries)
            {
                if (index[entry.Key].Digest is not { } digest) { return null; }
                BuildFingerprint.AppendPart(builder, entry.Key);
                BuildFingerprint.AppendPart(builder, digest);
            }
            return BuildFingerprint.HashText(builder.ToString());
        });
        public IReadOnlyList<KeyValuePair<string, T>> Entries { get; } = entries;

        public FrozenDictionary<string, (T Item, string? Digest)> Index { get; } = index;

    }
}
