using System.Collections;
using System.Collections.Frozen;
using System.Diagnostics.CodeAnalysis;
using Kiji.Hosting;
using Kiji.Rendering;

namespace Kiji;

/// <summary>A lazily loaded, dependency-aware dictionary of site content.</summary>
/// <remarks>
/// Resolve it through dependency injection. Keys are opaque references generated by Kiji for
/// looking an item up again in this dictionary; they are not URLs, slugs, domain identifiers,
/// or persistent identifiers.
/// </remarks>
public sealed class ContentDictionary<T> : IReadOnlyDictionary<string, T>
    where T : class
{
    private readonly ContentRuntime _runtime;
    private readonly Func<IServiceProvider, IReadOnlyList<(string Key, T Item, string? SourceFile)>> _load;

    internal ContentDictionary(
        ContentRuntime runtime,
        Func<IServiceProvider, IReadOnlyList<(string Key, T Item, string? SourceFile)>> load,
        string contentSetScope = "")
    {
        _runtime = runtime;
        _load = load;
        ContentSetScope = contentSetScope;
    }

    /// <summary>
    /// The number of items in the dictionary.
    /// </summary>
    public int Count => Observed.Entries.Count;

    /// <summary>
    /// Every opaque key, in source order.
    /// </summary>
    public IEnumerable<string> Keys => Observed.Entries.Select(static entry => entry.Key);

    /// <summary>
    /// Every item, in source order.
    /// </summary>
    public IEnumerable<T> Values => Observed.Entries.Select(static entry => entry.Value);

    /// <summary>
    /// The item with the given key, compared case-insensitively.
    /// </summary>
    /// <exception cref="KeyNotFoundException">No item carries that key.</exception>
    public T this[string key] => TryGetValue(key, out var item)
        ? item
        : throw new KeyNotFoundException($"Content item with key '{key}' was not found.");

    /// <summary>
    /// The content directory this dictionary reads, relative to the contents root;
    /// empty for the whole tree. Pages that enumerate it depend on this
    /// subtree rather than on every content file in the site.
    /// </summary>
    internal string ContentSetScope { get; }

    /// <summary>
    /// Finds an item by its key, compared case-insensitively.
    /// </summary>
    public bool TryGetValue(string key, [NotNullWhen(true)] out T? item)
    {
        ArgumentNullException.ThrowIfNull(key);

        var materialized = Materialized;
        if (!materialized.Index.TryGetValue(key, out item))
        {
            // A miss still observed the key set, so it is only valid while the key set
            // holds — that is the content set, not any one file.
            MarkContentSetDependency();
            return false;
        }

        RecordItemDependency(materialized, key);
        return true;
    }

    /// <summary>
    /// Whether an item with the given key exists.
    /// </summary>
    public bool ContainsKey(string key)
    {
        return TryGetValue(key, out _);
    }

    /// <inheritdoc/>
    public IEnumerator<KeyValuePair<string, T>> GetEnumerator()
    {
        return Observed.Entries.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    private MaterializedContent Materialized => _runtime.GetOrMaterialize(this, Materialize);

    /// <summary>
    /// The dictionary as seen by a member that exposes its shape (count, keys, values,
    /// enumeration). Observing the shape couples the page to the content set: a list
    /// page has to reflect items being added and removed, not just edited. Keyed
    /// lookups deliberately go through <see cref="Materialized"/> instead.
    /// </summary>
    private MaterializedContent Observed
    {
        get
        {
            MarkContentSetDependency();
            return Materialized;
        }
    }

    private void MarkContentSetDependency()
    {
        PageRenderContext.Current?.Dependencies?.MarkContentSetDependency(ContentSetScope);
    }

    private void RecordItemDependency(MaterializedContent materialized, string key)
    {
        var dependencies = PageRenderContext.Current?.Dependencies;
        if (dependencies is null)
        {
            return;
        }

        // A keyed lookup depends only on that item's source file when known;
        // untracked items fall back to the whole content set (conservative).
        if (materialized.ProvenanceByKey.TryGetValue(key, out var sourceFile) && sourceFile is not null)
        {
            dependencies.AddFile(sourceFile);
        }
        else
        {
            dependencies.MarkContentSetDependency(ContentSetScope);
        }
    }

    private MaterializedContent Materialize(IServiceProvider services)
    {
        var loaded = _load(services);

        var index = new Dictionary<string, T>(loaded.Count, StringComparer.OrdinalIgnoreCase);
        var provenanceByKey = new Dictionary<string, string?>(loaded.Count, StringComparer.OrdinalIgnoreCase);
        var entries = new KeyValuePair<string, T>[loaded.Count];
        for (var i = 0; i < loaded.Count; i++)
        {
            var (key, item, sourceFile) = loaded[i];
            if (string.IsNullOrWhiteSpace(key))
            {
                throw new InvalidOperationException(
                    $"The internal content loader for '{typeof(T).Name}' produced an empty key.");
            }

            if (!index.TryAdd(key, item))
            {
                throw new InvalidOperationException(
                    $"The internal content loader for '{typeof(T).Name}' produced duplicate key '{key}'.");
            }

            provenanceByKey[key] = sourceFile;
            entries[i] = new KeyValuePair<string, T>(key, item);
        }

        return new MaterializedContent(
            entries,
            index.ToFrozenDictionary(StringComparer.OrdinalIgnoreCase),
            provenanceByKey.ToFrozenDictionary(StringComparer.OrdinalIgnoreCase));
    }

    private sealed class MaterializedContent(
        IReadOnlyList<KeyValuePair<string, T>> entries,
        FrozenDictionary<string, T> index,
        FrozenDictionary<string, string?> provenanceByKey)
    {
        public IReadOnlyList<KeyValuePair<string, T>> Entries { get; } = entries;

        public FrozenDictionary<string, T> Index { get; } = index;

        public FrozenDictionary<string, string?> ProvenanceByKey { get; } = provenanceByKey;
    }
}
