<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <UseMicrosoftTestingPlatformRunner>true</UseMicrosoftTestingPlatformRunner>
    <NoWarn>$(NoWarn);CA1707;xUnit1051;CA1869</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Testing.Platform" />
    <PackageReference Include="xunit.v3" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../Kiji/Kiji.csproj" />
    <ProjectReference Include="../Kiji.Markdown/Kiji.Markdown.csproj" />
    <ProjectReference Include="../Kiji.Images/Kiji.Images.csproj" />
  </ItemGroup>

</Project>
